project:
  type: website
  output-dir: docs

website:
  title: "Sumedh's Blog"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: projects.qmd
        text: Blog

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



